import Head from 'next/head';
import { Inter } from 'next/font/google';
import Navbar from '@/pages/Navbar';
import { Box } from '@/pages/Card';
import { useState } from 'react';
import { useRouter } from 'next/router';

import { Button, TextInput } from "@mantine/core";
import { useForm } from '@mantine/form';
import { useUser } from '@auth0/nextjs-auth0/client';

const Form = () => {
  const form = useForm({
    initialValues: {
      subject: '',
      grade: '',
    },
    validate: {
      subject: (value) => (value.length < 2 ? 'Invalid subject' : null),
      grade: (value) => (value.length < 2 ? 'Invalid grade' : null),
    },
  });

  return form;
}

const Router = () => {
  const router = useRouter();

  return router;
}

export default function Quiz() {

  const router = useRouter();
  const data = router.query;
  console.log(data);

  const [overlay, setOverlay] = useState(false);

  const { user, error, isLoading } = useUser();

  if (isLoading) return <div>Loading...</div>;
  if (error) return <div>{error.message}</div>

  if (user) {

    const form = Form();

    const router = Router();

    const handleSubmit = async (e) => {
      e.preventDefault();

      console.log(form.values);

      router.push({
        pathname: '/dashboard/result',
        query: form.values,
      });
    }

    return (
      <>
        <Head>
          <title>QuizBurst | Play Quiz</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Navbar buttonText={"Sign Out 🙃"} buttonLink={"/api/auth/logout"} />
        <div
          className="dashboard-container"
          id="dashboard"
          style={{ margin: "160px 0", padding: "0 20px", position: "relative", height: "auto", width: "100%", display: "flex", flexDirection: "column", justifyContent: "space-evenly", alignItems: "" }}
        >
          <form onSubmit={handleSubmit} style={{ display: "flex", flexDirection: "column", gap: "20px" }}>
            <TextInput label="The sum of the interior angles of a triangle is always 180 degrees. (True/False) " required max={50} miw={280} {...form.getInputProps('subject')} />
            <TextInput label="The square root of 16 is 4. (True/False)  " required max={50} miw={280} {...form.getInputProps('grade')} />
            <TextInput label="A linear equation has a degree of 2. (True/False)  " required max={50} miw={280} {...form.getInputProps('grade')} />
            <TextInput label="The equation x^2 + 3x + 2 = 0 has two real solutions. (True/False)  " required max={50} miw={280} {...form.getInputProps('grade')} />
            <TextInput label="The value of π (pi) is an irrational number. (True/False)  " required max={50} miw={280} {...form.getInputProps('grade')} />
            <TextInput label="A parallelogram has opposite sides that are congruent. (True/False)  " required max={50} miw={280} {...form.getInputProps('grade')} />
            <TextInput label="The absolute value of any real number is always positive. (True/False)  " required max={50} miw={280} {...form.getInputProps('grade')} />
            <TextInput label="The decimal representation of 1/4 is 0.25. (True/False)  " required max={50} miw={280} {...form.getInputProps('grade')} />
            <TextInput label="The formula for the area of a circle is A = πr^2. (True/False)  " required max={50} miw={280} {...form.getInputProps('grade')} />
            <TextInput label="A right triangle can have two equal sides. (True/False)  " required max={50} miw={280} {...form.getInputProps('grade')} />
            <Button type="submit" style={{ marginTop: "20px", padding: "8px 32px" }} >Submit</Button>
          </form>
        </div>
      </>
    );
  }

  // eslint-disable-next-line @next/next/no-html-link-for-pages
  return <a href="/api/auth/login">Login</a>;
}

