/* eslint-disable @next/next/no-html-link-for-pages */
import Head from 'next/head';
import Navbar from '../Navbar';
import { Box } from '../Card';
import { Button, TextInput } from "@mantine/core";
import { useForm } from '@mantine/form';

import { useUser } from '@auth0/nextjs-auth0/client';
import { useRouter } from 'next/router';

const Form = () => {
  const form = useForm({
    initialValues: {
      subject: '',
      grade: '',
    },
    validate: {
      subject: (value) => (value.length < 2 ? 'Invalid subject' : null),
      grade: (value) => (value.length < 2 ? 'Invalid grade' : null),
    },
  });

  return form;
}

const Router = () => {
  const router = useRouter();

  return router;
}

export default function Dashboard() {

  const { user, error, isLoading } = useUser();

  if (isLoading) return <div>Loading...</div>;
  if (error) return <div>{error.message}</div>

  if (user) {

    const form = Form();

    const router = Router();

    const handleSubmit = async (e) => {
      e.preventDefault();

      console.log(form.values);

      router.push({
        pathname: '/dashboard/quiz',
        query: form.values,
      });
    }

    return (
      <>
        <Head>
          <title>QuizBurst | Dashboard</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Navbar buttonText={"Sign Out 🙃"} buttonLink={"/api/auth/logout"} />
        <div
          className="dashboard-container"
          id="dashboard"
          style={{ margin: 0, padding: 0, position: "relative", height: "100vh", width: "100%", display: "flex", flexDirection: "column", justifyContent: "space-evenly", alignItems: "center" }}
        >
          <Box text={`Hello, ${user.name}`} />
          <form onSubmit={handleSubmit} style={{display: "flex", flexDirection: "column", gap: "20px"}}>
            <TextInput label="What subject do you want to be quizzed on? " required max={50} miw={280} {...form.getInputProps('subject')} />
            <TextInput label="At what grade level are you studying?  " required max={50} miw={280} {...form.getInputProps('grade')} />
            <Button type="submit" style={{marginTop: "20px"}} >Play Quiz</Button>
          </form>
        </div>
      </>
    );
  }

  return <a href="/api/auth/login">Login</a>;
}
