import Head from 'next/head';
import Image from 'next/image';
import { Inter } from 'next/font/google';
import Script from 'next/script';
import Navbar from '../Navbar';
import Card from '../Card';

const inter = Inter({ subsets: ['latin'] });

export default function App() {
  return (
    <>
      <Head>
        <title>QuizBurst | Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar buttonText={"Sign Out 🙃"} buttonLink={"/api/auth/login"} />

      <div 
        className="dashboard-container"
        id="dashboard"
        style={{ margin: 0, padding: 0, position: "relative", height: "100vh", width: "100%", display: "flex", flexDirection: "row", justifyContent: "space-evenly", alignItems: "center" }}
      >
        <Card text={"Easy"} buttonLink={"/dashboard/easy"} />
        <Card text={"Medium"} buttonLink={"/dashboard/easy"} />
        <Card text={"Hard"} buttonLink={"/dashboard/easy"} />
      </div>
    </>
  )
}
