import Head from 'next/head';
import Image from 'next/image';
import { Inter } from 'next/font/google';
import Script from 'next/script';
import Navbar from '@/pages/Navbar';
import { Box } from '@/pages/Card';
import { useState } from 'react';

const inter = Inter({ subsets: ['latin'] });

const handleSubmit = () => {

}

export default function Easy() {

    const [overlay, setOverlay] = useState(false);

    return (
        <>
            <Head>
                <title>QuizBurst | Play Quiz | Easy</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Navbar buttonText={"Sign Out 🙃"} buttonLink={"/api/auth/login"} />

            <div
                className="easy-container"
                id="easy"
                style={{ margin: 0, padding: "0 20px", position: "relative", height: "100vh", width: "100%", display: "flex", flexDirection: "column", justifyContent: "center", alignItems: "center" }}
            >
                <Box text={"Q. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."} />
                <div className='easy-choices-container'>
                    {/* <div> */}
                        <Box text={"1. Lorem ipsum. "} style={{cursor: "pointer", minWidth: "280px"}} onClick={()=>handleSubmit("Lorem ipsum.")} />
                        <Box text={"2. Lorem ipsum. "} style={{cursor: "pointer", minWidth: "280px"}} onClick={()=>handleSubmit("Lorem ipsum.")} />
                    {/* </div> */}
                    {/* <div> */}
                        <Box text={"3. Lorem ipsum. "} style={{cursor: "pointer", minWidth: "280px"}} onClick={()=>handleSubmit("Lorem ipsum.")} />
                        <Box text={"4. Lorem ipsum. "} style={{cursor: "pointer", minWidth: "280px"}} onClick={()=>handleSubmit("Lorem ipsum.")} />
                    {/* </div> */}
                </div>
            </div>
        </>
    )
}
