import Head from 'next/head';
import Image from 'next/image';
import { Inter } from 'next/font/google';
import Navbar from './Navbar';
import Home from './Home';
import Script from 'next/script';

const inter = Inter({ subsets: ['latin'] });

export default function App() {
  return (
    <>
      <Head>
        <title>QuizBurst</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Script src="https://unpkg.com/@lottiefiles/lottie-player@latest/dist/lottie-player.js" />

      <Navbar buttonText={"Sign In 🙂"} buttonLink={"/api/auth/login"} />
      <Home />
    </>
  )
}
